version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
      - "44251:44251"

  hive-metastore-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hive
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  hive-metastore:
    image: apache/hive:3.1.3
    container_name: hive-metastore
    environment:
      HIVE_METASTORE_DB_HOST: hive-metastore-db
      HIVE_METASTORE_DB_NAME: metastore
      HIVE_METASTORE_DB_USER: hive
      HIVE_METASTORE_DB_PASS: hive
    depends_on:
      - hive-metastore-db
    ports:
      - "9083:9083"
    command: >
      /opt/hive/bin/hive --service metastore -p 9083
