version: '3.7'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3-compatible API
      - "9001:9001"  # Web console
    volumes:
      - minio_data:/data
    networks:
      - nessie_network

  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    container_name: nessie
    environment:
      QUARKUS_PROFILE: "prod"
      QUARKUS_HTTP_PORT: "19120"
    ports:
      - "19120:19120"  # Nessie REST API
    networks:
      - nessie_network

volumes:
  minio_data:

networks:
  nessie_network:
    driver: bridge
