services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3-compatible API
      - "9001:9001"  # Web console
    volumes:
      - minio_data:/data
    networks:
      - trino_network

  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    container_name: nessie
    environment:
      QUARKUS_PROFILE: "prod"
      QUARKUS_HTTP_PORT: "19120"
    ports:
      - "19120:19120"  # Nessie REST API
    networks:
      - trino_network

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"  # Expose Trino's Web UI
    volumes:
      - ./src:/etc/trino
      - ./data:/var/trino/data
    networks:
      - trino_network


volumes:
  minio_data:

networks:
  trino_network:
    driver: bridge